- hosts: web
  tasks:
  - name: "copy website"
    copy:
      src: site/index.html
      dest: /var/www/default
  - name: "replace website"
    replace:
      path: /var/www/default/index.html
      regexp: "host"
      replace: "{{ inventory_hostname }}"
